from .TrainingStrategy import TrainingStrategy
from .TokenClassificationStrategy import TokenClassificationStrategy
from .TextClassificationStrategy import TextClassificationStrategy
from .SemanticRoleLabellingStrategy import SemanticRoleLabellingStrategy
from .QuestionAnsweringStrategy import QuestionAnsweringStrategy