version: '3'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - pt-pump-up
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/build:/app/build
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
  
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: on-failure
    networks:
      - pt-pump-up
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - mongo_database=production

networks:
  pt-pump-up:
    driver: bridge