version: '3'

services:
  laravel:
    build: 
      context: ./backend/laravel
      dockerfile: dev.Dockerfile
    container_name: laravel    
    ports:
      - "8000:8000"
      - "5173:5173"
    networks:
      - pt-pump-up
    volumes:
      - ./backend/laravel:/app
      - node_modules:/app/node_modules
      - vendor:/app/vendor
  database:
    image: mysql:8
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    ports:
      - "3306:3306"
    networks:
      - pt-pump-up
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - pt-pump-up

networks:
  pt-pump-up:
    driver: bridge

volumes:
  node_modules:
  vendor:
  database: